### ISSUE TITLE
hi,hxd,你有没有将你实现的mobileoneblock添加到某个网络呢，能交流下吗

### ISSUE THREAD

**Issue by xinyiamazing** [ttjjmm/cv_model_zoo#1]

**Comment by ttjjmm** [comment]
这个mobileone代码还没写完，最近会写完，添加的话，需要对应的预训练权重在imagenet1k的会比较好，但原论文作者没有开源出来。

**Comment by ttjjmm** [comment]
facebook实现的：https://github.com/facebookresearch/mobile-vision/blob/4d5207c/mobile_cv/arch/fbnet_v2/mobileone_block.py#L15
